apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Release.Name}}-{{ .Chart.Name}}
  name: {{ .Release.Name}}-{{ .Chart.Name}}
spec:  
  type: {{ .Values.service.type}}
  ports:    
    - name: mongodb
      port: {{ .Values.service.port}}
      targetPort: 27017
  selector:
    app: {{ .Release.Name}}-{{ .Chart.Name}}
  type: NodePort
