apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "backend.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "backend.fullname" . }}
    spec:
      containers:
      - image: {{ .Values.image.repository}}:{{ .Values.image.tage}}
        imagePullPolicy: Always
        name: {{ include "backend.fullname" . }}
        ports:
        - name: {{ include "backend.fullname" . }}
          containerPort: 3000
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: {{ include "backend.fullname" . }}-secret
              key: mongodb-uri
